### ISSUE TITLE
player playing not worked

### ISSUE THREAD

**Issue by luofang** [lulop-k/kurento-rtsp2webrtc#30]
everything prepared, and no error. but no remote picture. the console log:

......
console.js:77 oniceconnectionstatechange -> checking
console.js:77 icegatheringstate -> gathering
console.js:77 oniceconnectionstatechange -> connected
console.js:77 icegatheringstate -> complete

**Comment by sraza295** [comment]
@lulop-k 
Did you fix this issue?
I am getting same error
